definitions:
  restapi.Book:
    properties:
      author:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample swagger for Books API
  title: Books Example API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: get list of books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/restapi.Book'
            type: array
      security:
      - ApiKeyAuth: []
      summary: get list of all books
      tags:
      - books
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
